General code update
goncasmage1/UINavigation pull request #150
Opened 2022-03-14 18:17 UTC by seb-exiin

Modify some typos in descriptions and some spaces here and there

2022-03-17 13:07 UTC, goncasmage1 requested changes

2022-03-17 13:07 UTC, goncasmage1 commented on Source/UINavigation/Public/UINavWidget.h
> +	*	@param  ZOrder order to display the widget
Don't forget to start with upper case

2022-03-17 13:07 UTC, goncasmage1 commented on Source/UINavigation/Private/UINavWidget.cpp
> +
I'd rather keep this as-is.

2022-03-17 13:07 UTC, goncasmage1 commented on Source/UINavigation/Private/UINavWidget.cpp
> -
I'd rather keep this as-is.

2022-03-17 13:07 UTC, goncasmage1 commented on Source/UINavigation/Private/UINavPCComponent.cpp
Maybe remove this line as well?

2022-03-17 13:07 UTC, goncasmage1 commented on Source/UINavigation/Private/UINavOptionBox.cpp
> +
I'd rather keep this as-is.

2022-03-17 13:07 UTC, goncasmage1 commented on Source/UINavigation/Private/UINavComponentBox.cpp
> +
I'd rather keep this as-is.

2022-03-17 13:07 UTC, goncasmage1 commented on Source/UINavigation/Public/UINavWidget.h
> +	*	@param Button  Required button type for the UI Navigation plugin
Simply describe as "Target UINavButton"

2022-03-17 13:07 UTC, goncasmage1 commented on Source/UINavigation/Public/UINavWidget.h
> +	*	@param  Button  Required button type for the UI Navigation plugin
Simply describe as "Target UINavButton"

2022-03-17 13:07 UTC, goncasmage1 commented on Source/UINavigation/Public/UINavWidget.h
> +	*	@param  ZOrder order to display the widget
Don't forget to start with upper case

2022-03-17 22:08 UTC, seb-exiin commented on Source/UINavigation/Public/UINavWidget.h
> +	*	@param  ZOrder order to display the widget
done

2022-03-17 22:09 UTC, seb-exiin commented on Source/UINavigation/Private/UINavPCComponent.cpp
done

2022-03-17 22:10 UTC, seb-exiin commented on Source/UINavigation/Private/UINavComponentBox.cpp
> +
done

2022-03-17 22:11 UTC, seb-exiin commented on Source/UINavigation/Public/UINavWidget.h
> +	*	@param Button  Required button type for the UI Navigation plugin
done

2022-03-17 22:12 UTC, seb-exiin commented on Source/UINavigation/Public/UINavWidget.h
> +	*	@param  Button  Required button type for the UI Navigation plugin
done

2022-03-17 22:12 UTC, seb-exiin commented on Source/UINavigation/Public/UINavWidget.h
> +	*	@param  ZOrder order to display the widget
done

2022-03-17 22:14 UTC, seb-exiin commented
changed applied, ready to re-review

2022-03-19 10:33 UTC, goncasmage1 approved these changes

2022-03-19 10:33 UTC, merged