Updating enhanced input bindings to use ETriggerEvent::Completed
goncasmage1/UINavigation pull request #155
Opened 2022-04-01 05:23 UTC by Peralysis

I came across an issue where UINavComponents in a grid would constantly cycle after pressing an directional key (WSAD or D-Pad). 

After some digging, I noticed that the Enhanced Input bindings are currently bound to `ETriggerEvent::Canceled`. Based on the description of the trigger events, I don't believe this is correct: https://github.com/EpicGames/UnrealEngine/blob/99b6e203a15d04fc7bbbf554c421a985c1ccb8f1/Engine/Plugins/Experimental/EnhancedInput/Source/EnhancedInput/Private/EnhancedPlayerInput.cpp#L11-L20.

Updating these bindings to use `ETriggerEvent::Completed` instead resolved this issue for me. During my testing, I was unable to uncover any adverse side effects.

2022-04-04 14:44 UTC, goncasmage1 commented
Please push into 5.0

2022-04-04 14:45 UTC, goncasmage1 requested changes
Please push into 5.0

2022-04-05 15:16 UTC, Peralysis commented
I took a look at the 5.0 branch, but it doesn't look like any of the Enhanced Input support has made it into that branch yet. I do see Enhanced Input support in the 4.27 branch, though, if you'd prefer me to update the PR branch to that instead.

2022-04-05 19:27 UTC, goncasmage1 commented
I'm merging 4.27 into 5.0 in order to integrate these changes. I'll let you know when they're done.

2022-04-05 20:31 UTC, goncasmage1 commented
@Peralysis I've merged 4.27 branch into 5.0. Please update this PR for that branch so that I can merge it and release the updated 5.0 version 😄

2022-04-05 20:42 UTC, Peralysis commented
Thank you! The PR base branch has been update to 5.0.

2022-04-06 06:47 UTC, goncasmage1 approved these changes

2022-04-06 06:47 UTC, merged